# Generated by Django 2.2.16 on 2021-12-22 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 7, 55, 47, 64029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 7, 55, 47, 64029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='1479871b96bc8cb34b3ec5cfe4c506', max_length=30, verbose_name='Код подтверждения'),
        ),
    ]
