# Generated by Django 2.2.16 on 2022-11-18 21:14

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='activity',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Активность (что бы это не значило)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ageLimits',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возрастное ограничение (вероятно)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='city',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='group',
            name='country',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='group',
            name='mainSection',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[reviews.models.validate_score], verbose_name='я хз, что это'),
        ),
        migrations.AlterField(
            model_name='group',
            name='membersCount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество участников'),
        ),
    ]
