# Generated by Django 2.2.16 on 2021-12-20 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveSmallIntegerField(default=42),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 1, 59, 22, 160120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.PositiveSmallIntegerField(default=42),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 1, 59, 22, 159621, tzinfo=utc)),
        ),
    ]
