# Generated by Django 2.2.16 on 2022-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221118_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mainSection',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='я хз, что это'),
        ),
    ]
